// If we're running in a web worker - which doesn't share global context with the main thread -
// we need to manually load dependencies that are not explicit- meaning our non-module dependencies
// generated by Bridge.Net
if (typeof document == 'undefined') {
    // monaco will run the worker from vs/base/worker so the relative path needs
    // to be from there (hence going up 2 dirs) This stinks because we're
    // requiring the host app to put files in specific locations
    importScripts(
        '../../language/kusto/bridge.min.js',
        '../../language/kusto/kusto.javascript.client.min.js',
        '../../language/kusto/Kusto.Language.Bridge.min.js'
    );
}

export * from './languageServiceESM';
