name: pr-builds
defaults:
  run:
on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: yarn install
        run: |
          yarn install --immutable

      - name: Check formatting
        run: yarn format:check

      - name: Creates release folder
        working-directory: package
        run: mkdir -p release

      - name: compile
        working-directory: package
        run: yarn compile

      - name: run release script
        working-directory: package
        run: node ./scripts/release.js

      - name: run bundle script
        working-directory: package
        run: node ./scripts/bundle.js

      - name: copy runtime dependencies to out folder
        working-directory: package
        run: yarn copy_runtime_deps_to_out

      - name: copy types to out folder
        working-directory: package
        run: yarn copy_types_to_release
